### ISSUE TITLE
not comply with psr-4

### ISSUE THREAD

**Issue by Flyfot-Finesse** [Apiipnet/php-apiip.net#1]
Hello, 

Thanks for the package but it isn't usable as it doesn't comply with PSR-4 standards. I followed the documentation on installation but doeson't work on Laravel Forge server, locally it works 

Here is the message 
`Class ApiipClient\Apiip located in ./vendor/apiip/apiip.net/src/apiip.php does not comply with psr-4 autoloading standard. Skipping.
`

An update to the package would be good. 

Thanks!

**Comment by Vojkan94** [comment]
Hello, thank you for your comment, please use a simple GET request, you can find our docs here: https://apiip.net/documentation
We will update the package in the near future.

**Comment by Apiipnet** [comment]
Hello, thank you for your comment, please use a simple GET request, you can find our docs here: https://apiip.net/documentation
We will update the package in the near future.

**Comment by Flyfot-Finesse** [comment]
hi @Apiipnet , 
thanks for the reply! 
Ok you mean direct GET request to the API without package yes can do that. I found a temporary fix though if it helps. I added the path in composer autoload classmap see screenshot below:
![image](https://github.com/Apiipnet/php-apiip.net/assets/49826588/48ccf225-922b-4e49-93ad-ff41c8046ebd)

**Comment by Apiipnet** [comment]
Fixed.
